// flow-typed signature: de4a822afc7dac850b65c8177283f33b
// flow-typed version: <<STUB>>/indicative_vhttps://github.com/Andreyco/indicative#764ed4838b82f0efb7c19b4960db3aad7fd95441/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'indicative'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'indicative' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'indicative/bin/index' {
  declare module.exports: any;
}

declare module 'indicative/examples/arrays' {
  declare module.exports: any;
}

declare module 'indicative/examples/sanitizor' {
  declare module.exports: any;
}

declare module 'indicative/examples/validator' {
  declare module.exports: any;
}

declare module 'indicative/src/Messages/index' {
  declare module.exports: any;
}

declare module 'indicative/src/Modes/index' {
  declare module.exports: any;
}

declare module 'indicative/src/Parser/index' {
  declare module.exports: any;
}

declare module 'indicative/src/Raw/index' {
  declare module.exports: any;
}

declare module 'indicative/src/Rule/index' {
  declare module.exports: any;
}

declare module 'indicative/src/Sanitization/filters' {
  declare module.exports: any;
}

declare module 'indicative/src/Sanitization/index' {
  declare module.exports: any;
}

declare module 'indicative/src/Validations/index' {
  declare module.exports: any;
}

declare module 'indicative/src/Validator/engine' {
  declare module.exports: any;
}

declare module 'indicative/src/Validator/index' {
  declare module.exports: any;
}

declare module 'indicative/test/messages.spec' {
  declare module.exports: any;
}

declare module 'indicative/test/parser.spec' {
  declare module.exports: any;
}

declare module 'indicative/test/raw.spec' {
  declare module.exports: any;
}

declare module 'indicative/test/sanitization.spec' {
  declare module.exports: any;
}

declare module 'indicative/test/validations.spec' {
  declare module.exports: any;
}

declare module 'indicative/test/validator.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'indicative/bin/index.js' {
  declare module.exports: $Exports<'indicative/bin/index'>;
}
declare module 'indicative/examples/arrays.js' {
  declare module.exports: $Exports<'indicative/examples/arrays'>;
}
declare module 'indicative/examples/sanitizor.js' {
  declare module.exports: $Exports<'indicative/examples/sanitizor'>;
}
declare module 'indicative/examples/validator.js' {
  declare module.exports: $Exports<'indicative/examples/validator'>;
}
declare module 'indicative/index' {
  declare module.exports: $Exports<'indicative'>;
}
declare module 'indicative/index.js' {
  declare module.exports: $Exports<'indicative'>;
}
declare module 'indicative/src/Messages/index.js' {
  declare module.exports: $Exports<'indicative/src/Messages/index'>;
}
declare module 'indicative/src/Modes/index.js' {
  declare module.exports: $Exports<'indicative/src/Modes/index'>;
}
declare module 'indicative/src/Parser/index.js' {
  declare module.exports: $Exports<'indicative/src/Parser/index'>;
}
declare module 'indicative/src/Raw/index.js' {
  declare module.exports: $Exports<'indicative/src/Raw/index'>;
}
declare module 'indicative/src/Rule/index.js' {
  declare module.exports: $Exports<'indicative/src/Rule/index'>;
}
declare module 'indicative/src/Sanitization/filters.js' {
  declare module.exports: $Exports<'indicative/src/Sanitization/filters'>;
}
declare module 'indicative/src/Sanitization/index.js' {
  declare module.exports: $Exports<'indicative/src/Sanitization/index'>;
}
declare module 'indicative/src/Validations/index.js' {
  declare module.exports: $Exports<'indicative/src/Validations/index'>;
}
declare module 'indicative/src/Validator/engine.js' {
  declare module.exports: $Exports<'indicative/src/Validator/engine'>;
}
declare module 'indicative/src/Validator/index.js' {
  declare module.exports: $Exports<'indicative/src/Validator/index'>;
}
declare module 'indicative/test/messages.spec.js' {
  declare module.exports: $Exports<'indicative/test/messages.spec'>;
}
declare module 'indicative/test/parser.spec.js' {
  declare module.exports: $Exports<'indicative/test/parser.spec'>;
}
declare module 'indicative/test/raw.spec.js' {
  declare module.exports: $Exports<'indicative/test/raw.spec'>;
}
declare module 'indicative/test/sanitization.spec.js' {
  declare module.exports: $Exports<'indicative/test/sanitization.spec'>;
}
declare module 'indicative/test/validations.spec.js' {
  declare module.exports: $Exports<'indicative/test/validations.spec'>;
}
declare module 'indicative/test/validator.spec.js' {
  declare module.exports: $Exports<'indicative/test/validator.spec'>;
}
