// flow-typed signature: 454d17fff6b1fdd35541a12d281ce142
// flow-typed version: <<STUB>>/indicative_v^2.2.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'indicative'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'indicative' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'indicative/examples/arrays' {
  declare module.exports: any;
}

declare module 'indicative/examples/sanitizor' {
  declare module.exports: any;
}

declare module 'indicative/examples/validator' {
  declare module.exports: any;
}

declare module 'indicative/src/Messages/index' {
  declare module.exports: any;
}

declare module 'indicative/src/Modes/index' {
  declare module.exports: any;
}

declare module 'indicative/src/Parser/index' {
  declare module.exports: any;
}

declare module 'indicative/src/Raw/index' {
  declare module.exports: any;
}

declare module 'indicative/src/Sanitization/filters' {
  declare module.exports: any;
}

declare module 'indicative/src/Sanitization/index' {
  declare module.exports: any;
}

declare module 'indicative/src/Validations/index' {
  declare module.exports: any;
}

declare module 'indicative/src/Validator/engine' {
  declare module.exports: any;
}

declare module 'indicative/src/Validator/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'indicative/examples/arrays.js' {
  declare module.exports: $Exports<'indicative/examples/arrays'>;
}
declare module 'indicative/examples/sanitizor.js' {
  declare module.exports: $Exports<'indicative/examples/sanitizor'>;
}
declare module 'indicative/examples/validator.js' {
  declare module.exports: $Exports<'indicative/examples/validator'>;
}
declare module 'indicative/index' {
  declare module.exports: $Exports<'indicative'>;
}
declare module 'indicative/index.js' {
  declare module.exports: $Exports<'indicative'>;
}
declare module 'indicative/src/Messages/index.js' {
  declare module.exports: $Exports<'indicative/src/Messages/index'>;
}
declare module 'indicative/src/Modes/index.js' {
  declare module.exports: $Exports<'indicative/src/Modes/index'>;
}
declare module 'indicative/src/Parser/index.js' {
  declare module.exports: $Exports<'indicative/src/Parser/index'>;
}
declare module 'indicative/src/Raw/index.js' {
  declare module.exports: $Exports<'indicative/src/Raw/index'>;
}
declare module 'indicative/src/Sanitization/filters.js' {
  declare module.exports: $Exports<'indicative/src/Sanitization/filters'>;
}
declare module 'indicative/src/Sanitization/index.js' {
  declare module.exports: $Exports<'indicative/src/Sanitization/index'>;
}
declare module 'indicative/src/Validations/index.js' {
  declare module.exports: $Exports<'indicative/src/Validations/index'>;
}
declare module 'indicative/src/Validator/engine.js' {
  declare module.exports: $Exports<'indicative/src/Validator/engine'>;
}
declare module 'indicative/src/Validator/index.js' {
  declare module.exports: $Exports<'indicative/src/Validator/index'>;
}
