// flow-typed signature: 37d44db33b5d1d4f18d370a5f4e7030b
// flow-typed version: <<STUB>>/mobile-center-analytics_v^0.10.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mobile-center-analytics'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mobile-center-analytics' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mobile-center-analytics/Analytics' {
  declare module.exports: any;
}

declare module 'mobile-center-analytics/scripts/postlink' {
  declare module.exports: any;
}

declare module 'mobile-center-analytics/scripts/prelink' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mobile-center-analytics/Analytics.js' {
  declare module.exports: $Exports<'mobile-center-analytics/Analytics'>;
}
declare module 'mobile-center-analytics/scripts/postlink.js' {
  declare module.exports: $Exports<'mobile-center-analytics/scripts/postlink'>;
}
declare module 'mobile-center-analytics/scripts/prelink.js' {
  declare module.exports: $Exports<'mobile-center-analytics/scripts/prelink'>;
}
