// flow-typed signature: cf6392d962ea8132320926db2602fef7
// flow-typed version: <<STUB>>/mobile-center_v^0.10.0/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mobile-center'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mobile-center' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mobile-center/__tests__/MobileCenter.test' {
  declare module.exports: any;
}

declare module 'mobile-center/mobile-center-log' {
  declare module.exports: any;
}

declare module 'mobile-center/MobileCenter' {
  declare module.exports: any;
}

declare module 'mobile-center/scripts/postlink' {
  declare module.exports: any;
}

declare module 'mobile-center/scripts/prelink' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mobile-center/__tests__/MobileCenter.test.js' {
  declare module.exports: $Exports<'mobile-center/__tests__/MobileCenter.test'>;
}
declare module 'mobile-center/mobile-center-log.js' {
  declare module.exports: $Exports<'mobile-center/mobile-center-log'>;
}
declare module 'mobile-center/MobileCenter.js' {
  declare module.exports: $Exports<'mobile-center/MobileCenter'>;
}
declare module 'mobile-center/scripts/postlink.js' {
  declare module.exports: $Exports<'mobile-center/scripts/postlink'>;
}
declare module 'mobile-center/scripts/prelink.js' {
  declare module.exports: $Exports<'mobile-center/scripts/prelink'>;
}
