// flow-typed signature: 094f04cb39a9edd22cd6c4981c4e4e54
// flow-typed version: <<STUB>>/plural-parens_v^1.0.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'plural-parens'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'plural-parens' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'plural-parens/test/spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'plural-parens/index' {
  declare module.exports: $Exports<'plural-parens'>;
}
declare module 'plural-parens/index.js' {
  declare module.exports: $Exports<'plural-parens'>;
}
declare module 'plural-parens/test/spec.js' {
  declare module.exports: $Exports<'plural-parens/test/spec'>;
}
