// flow-typed signature: c9d687958a7fb6ca8d4ff90a07f0700a
// flow-typed version: <<STUB>>/react-native-lightbox_v^0.7.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-lightbox'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-lightbox' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-lightbox/Lightbox' {
  declare module.exports: any;
}

declare module 'react-native-lightbox/LightboxOverlay' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-lightbox/Lightbox.js' {
  declare module.exports: $Exports<'react-native-lightbox/Lightbox'>;
}
declare module 'react-native-lightbox/LightboxOverlay.js' {
  declare module.exports: $Exports<'react-native-lightbox/LightboxOverlay'>;
}
