// flow-typed signature: 7eb32680525c66d58d7ebc43b31a9b43
// flow-typed version: <<STUB>>/react-native-portal_v^1.2.1/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-portal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-portal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-portal/rollup.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-portal/index' {
  declare module.exports: $Exports<'react-native-portal'>;
}
declare module 'react-native-portal/index.js' {
  declare module.exports: $Exports<'react-native-portal'>;
}
declare module 'react-native-portal/rollup.config.js' {
  declare module.exports: $Exports<'react-native-portal/rollup.config'>;
}
