// flow-typed signature: ad86edf76eefd71e5e91fd82e6eb0983
// flow-typed version: <<STUB>>/react-native-keyboard-manager_v^4.0.13-4/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-keyboard-manager'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-keyboard-manager' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-keyboard-manager/index' {
  declare module.exports: $Exports<'react-native-keyboard-manager'>;
}
declare module 'react-native-keyboard-manager/index.js' {
  declare module.exports: $Exports<'react-native-keyboard-manager'>;
}
