// flow-typed signature: 011456c03d19d443dca6146bb3a18984
// flow-typed version: <<STUB>>/react-native-contacts_v^1.0.2/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-contacts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-contacts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-contacts/index' {
  declare module.exports: $Exports<'react-native-contacts'>;
}
declare module 'react-native-contacts/index.js' {
  declare module.exports: $Exports<'react-native-contacts'>;
}
