// flow-typed signature: 6ea209aa756efa091031839932f3afeb
// flow-typed version: <<STUB>>/react-native-payments-cli_v^0.2.0/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-payments-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-payments-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-payments-cli/lib/commands' {
  declare module.exports: any;
}

declare module 'react-native-payments-cli/lib/helpers' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-payments-cli/index' {
  declare module.exports: $Exports<'react-native-payments-cli'>;
}
declare module 'react-native-payments-cli/index.js' {
  declare module.exports: $Exports<'react-native-payments-cli'>;
}
declare module 'react-native-payments-cli/lib/commands.js' {
  declare module.exports: $Exports<'react-native-payments-cli/lib/commands'>;
}
declare module 'react-native-payments-cli/lib/helpers.js' {
  declare module.exports: $Exports<'react-native-payments-cli/lib/helpers'>;
}
