// flow-typed signature: 3ad104022d8e4ab944bd8ab618eb44ae
// flow-typed version: <<STUB>>/react-fetch-component_v^5.0.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-fetch-component'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-fetch-component' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-fetch-component/dist/Fetch' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-fetch-component/dist/Fetch.js' {
  declare module.exports: $Exports<'react-fetch-component/dist/Fetch'>;
}
