// flow-typed signature: ae4b1d557f0b644048efd3c2ee5a729e
// flow-typed version: <<STUB>>/react-native-braintree-xplat_vhttps://github.com/kraffslol/react-native-braintree-xplat#343bd3c8553bb418c0a36deac240dc56e2209a6b/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-braintree-xplat'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-braintree-xplat' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-braintree-xplat/example/index.android' {
  declare module.exports: any;
}

declare module 'react-native-braintree-xplat/example/index.ios' {
  declare module.exports: any;
}

declare module 'react-native-braintree-xplat/index.android' {
  declare module.exports: any;
}

declare module 'react-native-braintree-xplat/index.ios' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-braintree-xplat/example/index.android.js' {
  declare module.exports: $Exports<'react-native-braintree-xplat/example/index.android'>;
}
declare module 'react-native-braintree-xplat/example/index.ios.js' {
  declare module.exports: $Exports<'react-native-braintree-xplat/example/index.ios'>;
}
declare module 'react-native-braintree-xplat/index.android.js' {
  declare module.exports: $Exports<'react-native-braintree-xplat/index.android'>;
}
declare module 'react-native-braintree-xplat/index.ios.js' {
  declare module.exports: $Exports<'react-native-braintree-xplat/index.ios'>;
}
