// flow-typed signature: abae9dc68a0aa6451a76b4535220d0dd
// flow-typed version: <<STUB>>/react-native-payments_v./3rdparty/react-native-payments/packages/react-native-payments/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-payments'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-payments' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-payments/bin' {
  declare module.exports: any;
}

declare module 'react-native-payments/lib/js/__mocks__/index' {
  declare module.exports: any;
}

declare module 'react-native-payments/lib/js/__tests__/constants-test' {
  declare module.exports: any;
}

declare module 'react-native-payments/lib/js/__tests__/PaymentRequest-test' {
  declare module.exports: any;
}

declare module 'react-native-payments/lib/js/__tests__/PaymentRequestUpdateEvent-test' {
  declare module.exports: any;
}

declare module 'react-native-payments/lib/js/__tests__/PaymentResponse-test' {
  declare module.exports: any;
}

declare module 'react-native-payments/lib/js/constants' {
  declare module.exports: any;
}

declare module 'react-native-payments/lib/js/errors/__tests__/index-test' {
  declare module.exports: any;
}

declare module 'react-native-payments/lib/js/errors/index' {
  declare module.exports: any;
}

declare module 'react-native-payments/lib/js/helpers/__tests__/index-test' {
  declare module.exports: any;
}

declare module 'react-native-payments/lib/js/helpers/index' {
  declare module.exports: any;
}

declare module 'react-native-payments/lib/js/index' {
  declare module.exports: any;
}

declare module 'react-native-payments/lib/js/NativePayments' {
  declare module.exports: any;
}

declare module 'react-native-payments/lib/js/PaymentRequest' {
  declare module.exports: any;
}

declare module 'react-native-payments/lib/js/PaymentRequestUpdateEvent' {
  declare module.exports: any;
}

declare module 'react-native-payments/lib/js/PaymentResponse' {
  declare module.exports: any;
}

declare module 'react-native-payments/lib/js/types' {
  declare module.exports: any;
}

declare module 'react-native-payments/lib/js/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-payments/bin.js' {
  declare module.exports: $Exports<'react-native-payments/bin'>;
}
declare module 'react-native-payments/index' {
  declare module.exports: $Exports<'react-native-payments'>;
}
declare module 'react-native-payments/index.js' {
  declare module.exports: $Exports<'react-native-payments'>;
}
declare module 'react-native-payments/lib/js/__mocks__/index.js' {
  declare module.exports: $Exports<'react-native-payments/lib/js/__mocks__/index'>;
}
declare module 'react-native-payments/lib/js/__tests__/constants-test.js' {
  declare module.exports: $Exports<'react-native-payments/lib/js/__tests__/constants-test'>;
}
declare module 'react-native-payments/lib/js/__tests__/PaymentRequest-test.js' {
  declare module.exports: $Exports<'react-native-payments/lib/js/__tests__/PaymentRequest-test'>;
}
declare module 'react-native-payments/lib/js/__tests__/PaymentRequestUpdateEvent-test.js' {
  declare module.exports: $Exports<'react-native-payments/lib/js/__tests__/PaymentRequestUpdateEvent-test'>;
}
declare module 'react-native-payments/lib/js/__tests__/PaymentResponse-test.js' {
  declare module.exports: $Exports<'react-native-payments/lib/js/__tests__/PaymentResponse-test'>;
}
declare module 'react-native-payments/lib/js/constants.js' {
  declare module.exports: $Exports<'react-native-payments/lib/js/constants'>;
}
declare module 'react-native-payments/lib/js/errors/__tests__/index-test.js' {
  declare module.exports: $Exports<'react-native-payments/lib/js/errors/__tests__/index-test'>;
}
declare module 'react-native-payments/lib/js/errors/index.js' {
  declare module.exports: $Exports<'react-native-payments/lib/js/errors/index'>;
}
declare module 'react-native-payments/lib/js/helpers/__tests__/index-test.js' {
  declare module.exports: $Exports<'react-native-payments/lib/js/helpers/__tests__/index-test'>;
}
declare module 'react-native-payments/lib/js/helpers/index.js' {
  declare module.exports: $Exports<'react-native-payments/lib/js/helpers/index'>;
}
declare module 'react-native-payments/lib/js/index.js' {
  declare module.exports: $Exports<'react-native-payments/lib/js/index'>;
}
declare module 'react-native-payments/lib/js/NativePayments.js' {
  declare module.exports: $Exports<'react-native-payments/lib/js/NativePayments'>;
}
declare module 'react-native-payments/lib/js/PaymentRequest.js' {
  declare module.exports: $Exports<'react-native-payments/lib/js/PaymentRequest'>;
}
declare module 'react-native-payments/lib/js/PaymentRequestUpdateEvent.js' {
  declare module.exports: $Exports<'react-native-payments/lib/js/PaymentRequestUpdateEvent'>;
}
declare module 'react-native-payments/lib/js/PaymentResponse.js' {
  declare module.exports: $Exports<'react-native-payments/lib/js/PaymentResponse'>;
}
declare module 'react-native-payments/lib/js/types.js' {
  declare module.exports: $Exports<'react-native-payments/lib/js/types'>;
}
declare module 'react-native-payments/lib/js/utils.js' {
  declare module.exports: $Exports<'react-native-payments/lib/js/utils'>;
}
