// flow-typed signature: 75c8917c540f98d4e9647691da3583a3
// flow-typed version: <<STUB>>/react-native-tableview-simple_v^0.16.13/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-tableview-simple'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-tableview-simple' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-tableview-simple/components/Cell' {
  declare module.exports: any;
}

declare module 'react-native-tableview-simple/components/Section' {
  declare module.exports: any;
}

declare module 'react-native-tableview-simple/components/Separator' {
  declare module.exports: any;
}

declare module 'react-native-tableview-simple/components/TableView' {
  declare module.exports: any;
}

declare module 'react-native-tableview-simple/components/__tests__/Cell-Basic.test' {
  declare module.exports: any;
}

declare module 'react-native-tableview-simple/components/__tests__/Cell-LeftDetail.test' {
  declare module.exports: any;
}

declare module 'react-native-tableview-simple/components/__tests__/Cell-RightDetail.test' {
  declare module.exports: any;
}

declare module 'react-native-tableview-simple/components/__tests__/Cell-Subtitle' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-tableview-simple/components/Cell.js' {
  declare module.exports: $Exports<'react-native-tableview-simple/components/Cell'>;
}
declare module 'react-native-tableview-simple/components/Section.js' {
  declare module.exports: $Exports<'react-native-tableview-simple/components/Section'>;
}
declare module 'react-native-tableview-simple/components/Separator.js' {
  declare module.exports: $Exports<'react-native-tableview-simple/components/Separator'>;
}
declare module 'react-native-tableview-simple/components/TableView.js' {
  declare module.exports: $Exports<'react-native-tableview-simple/components/TableView'>;
}
declare module 'react-native-tableview-simple/components/__tests__/Cell-Basic.test.js' {
  declare module.exports: $Exports<'react-native-tableview-simple/components/__tests__/Cell-Basic.test'>;
}
declare module 'react-native-tableview-simple/components/__tests__/Cell-LeftDetail.test.js' {
  declare module.exports: $Exports<'react-native-tableview-simple/components/__tests__/Cell-LeftDetail.test'>;
}
declare module 'react-native-tableview-simple/components/__tests__/Cell-RightDetail.test.js' {
  declare module.exports: $Exports<'react-native-tableview-simple/components/__tests__/Cell-RightDetail.test'>;
}
declare module 'react-native-tableview-simple/components/__tests__/Cell-Subtitle.js' {
  declare module.exports: $Exports<'react-native-tableview-simple/components/__tests__/Cell-Subtitle'>;
}
declare module 'react-native-tableview-simple/index' {
  declare module.exports: $Exports<'react-native-tableview-simple'>;
}
declare module 'react-native-tableview-simple/index.js' {
  declare module.exports: $Exports<'react-native-tableview-simple'>;
}
