// flow-typed signature: e05dde90df71ad7e621ee308b4d905f7
// flow-typed version: <<STUB>>/react-native-payments-addon-braintree_v./3rdparty/react-native-payments/packages/react-native-payments-addon-braintree/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-payments-addon-braintree'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-payments-addon-braintree' {
  declare module.exports: any;
}
